global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Globalization;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Text;
global using JetBrains.Annotations;
global using Spectre.Console;
global using Spectre.Tui.Ansi;